### ISSUE TITLE
Better support for `SwiftyMocky` configuration in `.sourcery.yml` file.

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#152]
At the moment it is possible to configure `SwiftyMocky` using `.sourcey.yml`

```yaml
sources:
    - Project_Name
    - Sourcery/Templates/PhantomProtocols.swift
templates:
    - Sourcery/Templates
    - ./Pods/SwiftyMocky/Sources/Templates
output:
    Sourcery/Generated
args:
    testable:
        - Project_Name
    import:
        - RxSwift
        - CoreData
        - SwiftyJSON
```

It will be nice to expand `SwiftyMocky` configuration in this file with better (self-explanatory) structure.

For example
```yaml
sources:
    - Project_Name
    - Sourcery/Templates/PhantomProtocols.swift
templates:
    - Sourcery/Templates
    - ./Pods/SwiftyMocky/Sources/Templates
output:
    Sourcery/Generated
args:
    swifty_mocky:
        testable:
            - Project_Name
        import:  
            - RxSwift
            - CoreData
            - SwiftyJSON
``` 

It gives possibility to Sourcery already users to keep `SwiftyMocky` separated without the need for create `.mocky.yaml`.
